#                               __                           __                  _  __
#                              / /  ___  ___ _ ___  ___  ___/ /___ _ ____ __ __ | |/_/
#                             / /__/ -_)/ _ `// -_)/ _ \/ _  // _ `// __// // /_>  <
#                            /____/\__/ \_, / \__//_//_/\_,_/ \_,_//_/   \_, //_/|_|
#                                      /___/                            /___/
Settings:
  #Hány checker fusson egyszerre maximum
  threads: 200

  #Proxy típus (socks4, socks5, https)
  proxy_type: socks4

  #Hány másodpercet várjon a weboldal betöltéséhez
  timeout: 8
